//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studyBuddy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumComment
    {
        public long ID { get; set; }
        public int userID { get; set; }
        public long forumID { get; set; }
        public string comment { get; set; }
        public int time { get; set; }
    }
}
